---
- hosts: all
  roles:
  - role: ansible-role-iptables-raw

  tasks:

  # - allow established/related inbound/outbound
  # - allow ssh inbound
  # - block http outbound
  # - allow all other outbound
  - name: Create iptables test rules
    iptables_raw:
      name: test_rules
      keep_unmanaged: no
      rules: |
        -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
        -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
        -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
        -A OUTPUT -p tcp -m tcp --dport 80 -j REJECT
        -A INPUT -j REJECT
        -A FORWARD -j REJECT
        -A OUTPUT -j ACCEPT
      state: present
