---
# tasks file for iptables-raw

- name: iptables-raw | install iptables services
  yum:
    name: iptables-services
    state: present

- name: iptables-raw | disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: iptables-raw | enable iptables
  service:
    name: iptables
    state: started
    enabled: yes
